---
title: "Kelly Wang"
output: 
  html_document:
    toc: true
    toc_float: true
---
<style type="text/css">
h1.title{text-align: center'}
</style>

<center>
# Resume
kzw2102@columbia.edu|[linkedin](https://www.linkedin.com/in/kellyzwang/)
</center>


## Education 

### Columbia University, Mailman School of Public Health | New York, NY 
**Master of Public Health in Biostatistics, Certificate in Health of an Aging Society** | Expected: May 2020 

*Relevant Coursework: Analysis of Categorical Data, Statstical Computing in SAS, Applied Regression I, The Global Politics of Aging, Research Methods and Applications, Data Science I, Applied Regression II, Probability, and Social Dimensions of Aging* 

### Brandeis University | Waltham, MA
**Bachelor of Science (BS), Concentration in Health: Science, Society, and Policy, Minor: Mathematics and South Asian Studies** | December 2017

### University of Botswana | Gaborone, Botswana
**Study Abroad ** | Summer 2016
*Coursework: Setswana Language, Pre-Professional Health Care, Community Practicum*

---
## Research Experience 
### Sergievsky Center/Taub Institute: Columbia University Medical Center** | New York, NY
*Graduate Research Assistant/Data Analyst* | Mar 2019 - Present 

  * Investigate the association between psychosocial factors and its role on longevity on a cohort of individuals with Down Syndrome, ages 30 and older by reviewing datasets consisting of over 600 participants
  * Independently research health literature and journal publications to identify possible statistical methods
  * Utilized SAS for data cleaning, data manipulation, data transformation, and other statistical procedures

### Global Healthy Living Foundation |New York, NY
*Summer Research Fellow* | May 2019 - August 2019

  * Utilized statistical procedures in SAS for an abstract and poster presented at the 2019 PAINWEEK conference
  * Led creation of all the materials needed for the pilot focus group conducted for the Eugene Washington Award Diversifying, Expanding, and Tracking Patient Engagement in Arthritis Research including the protocol, slide deck, flyers, and Q&A form that was distributed to various Naturally Occurring Retirement Communities (NORCs) in New York City. 
  
### Massachusetts Advocates for Nursing Home Reform | Medford, MA 
*Relaunch Intern* | December 2016 - December 2017
  * Supervised production of Crowdrise fundraising campaign to preserve organization; researched supporting evidence for campaign video script, created donation page, and executed on-campus event 
  * Analyzed qualitative statistical data on quality of care of 35 Massachusetts nursing homes for board presentation 
  * Conducted and analyzed responses from survey dataset of 250 Massachusetts baby boomers’ reactions to nursing homes in Massachusetts for PR Newswire Article

---
## Leadership Experience 
**Columbia University: Office of Educational Programming** | New York, NY
*Graduate Teaching Assistant* 
  * Analysis of Categorical Data | Statistical Computing with SAS | January 2020 - Present
  * Research Methods & Application: Quantitative Foundations | September 2019 - December 2019 
  
---
## Skills

  * Proficient in Microsoft Office Programs (MS Word, PowerPoint, Excel, Outlook)
  * Working knowledge in SAS, Java, SQL, R
  * Fluent in Chinese and English. Beginner level in French 

  
  







